#!/bin/zsh

export PATH=$HOME/.local/bin:$PATH
export PATH=$HOME/Devlopment/Python/bin:$PATH
export PATH=/home/islam/node_modules/.bin:$PATH
# export PATH=$HOME/Devlopment/nodejs/bin:$PATH
export C_INCLUDE_PATH="$HOME/.local/include:$C_INCLUDE_PATH"
export LIBRARY_PATH="$HOME/.local/lib:$LIBRARY_PATH"
export LD_LIBRARY_PATH="$HOME/.local/lib:$LD_LIBRARY_PATH"
# export NVM_DIR="$HOME/.nvm"
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
