#!/bin/zsh
export ANDROID_HOME=$HOME/Devlopment/Android/Sdk
export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools
export CHROME_EXECUTABLE=/usr/bin/brave-browser
export PATH="/home/islam/Devlopment/Android/Sdk/cmdline-tools/latest/bin/:$PATH"
export PATH="$PATH":"$HOME/.pub-cache/bin:$PATH"
export PATH="$PATH":"$HOME/.local/bin:$PATH"
export PATH="~/Devlopment/flutter/bin:$PATH"

